#!/bin/bash
# 'ns' stands for 'new script'
# it creates a new standard executable shell script then opens it in xed and asks for execution.
# usage : $ ns new_script_name_without_spaces
# or $ ns and will ask for a name
# setup : $ sudo cp ns usr/local/bin/ns && sudo chmod +x usr/local/bin/ns

if [[ $1 = "" ]] ; then
	echo "Nom du script à créer, sans extension :" && read NomNewScript
	else
	NomNewScript="$1"
fi

NewScript="$NomNewScript.sh"
# s'il existe déjà on arrête là hein mais on prévient
touch "$NewScript"
chmod +x $NewScript

echo "# !/bin/bash" >> $NewScript
echo "# $NewScript a été créé avec la commande ns" >> $NewScript
echo "# Setup :" >> $NewScript
echo "#" >> $NewScript
echo "# Usage de $NewScript :" >> $NewScript
echo "# $NewScript -flag -option " >> $NewScript
echo ""
echo "" # lol ou préparer un template et le cp :p
echo ""
echo "exit 0" >> $NewScript

xed $NewScript && echo "Executer $NewScript ? y/N" && read Answer
if [[ $Answer = "y" ]] ; then
	./$NewScript
	else
	exit 0
fi

exit 0
# script
# ```


